# Generated by Django 5.2.1 on 2025-08-18 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_mercadopagoaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mercadopago_access_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mercadopago_refresh_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mercadopago_user_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='MercadoPagoAccount',
        ),
    ]
