# Generated by Django 5.2.1 on 2025-06-18 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ofrece_servicios',
            field=models.BooleanField(default=False),
        ),
    ]
