services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d app || exit 1"]
      interval: 2s
      timeout: 2s
      retries: 30

  web:
    build: .
    entrypoint: []                 # ← por si la imagen arrastra un ENTRYPOINT
    command: sh -lc "./start.sh"
    env_file: .env
    environment:
      DJANGO_SETTINGS_MODULE: teden.settings
      PORT: "8000"
      DB_HOST: db
      DB_PORT: "5432"
      DB_USER: app
      DB_NAME: app
      DB_PASSWORD: app
      DEBUG: "1"
      SECRET_KEY: "dev-secret-key-change-me"
      DJANGO_SUPERUSER_USERNAME: admin
      DJANGO_SUPERUSER_EMAIL: admin@example.com
      DJANGO_SUPERUSER_PASSWORD: admin123
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - .:/app

volumes:
  pgdata: