# Generated by Django 5.2.1 on 2025-07-27 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MercadoPagoCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=255)),
                ('public_key', models.CharField(blank=True, max_length=255, null=True)),
                ('refresh_token', models.CharField(blank=True, max_length=255, null=True)),
                ('user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('live_mode', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SellerPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('starter', 'TEDEN Starter'), ('plus', 'TEDEN Plus'), ('pro', 'TEDEN Pro')], max_length=50, unique=True)),
                ('description', models.TextField()),
                ('monthly_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('max_products', models.PositiveIntegerField(blank=True, null=True)),
                ('max_services', models.PositiveIntegerField(blank=True, null=True)),
                ('max_stores', models.PositiveIntegerField(blank=True, null=True)),
                ('promoted_products', models.PositiveIntegerField(default=0)),
                ('commission_percent', models.DecimalField(decimal_places=2, default=20.0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mercadopagocredential', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller_profile_reverse', to='plans.mercadopagocredential')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plans.sellerplan')),
            ],
        ),
    ]
