# Generated by Django 5.2.1 on 2025-07-03 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('starter', 'TEDEN Starter'), ('plus', 'TEDEN Plus'), ('pro', 'TEDEN Pro')], max_length=50, unique=True)),
                ('description', models.TextField()),
                ('monthly_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('max_products', models.PositiveIntegerField(blank=True, null=True)),
                ('max_services', models.PositiveIntegerField(blank=True, null=True)),
                ('max_stores', models.PositiveIntegerField(blank=True, null=True)),
                ('promoted_products', models.PositiveIntegerField(default=0)),
                ('commission_percent', models.DecimalField(decimal_places=2, default=20.0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plans.sellerplan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
