# Generated by Django 5.2.1 on 2025-08-18 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_seed_default_plans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mercadopagocredential',
            name='user_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
