# Generated by Django 5.2.1 on 2025-07-27 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.CharField(choices=[('unpaid', 'No pagado'), ('paid', 'Pagado')], default='unpaid', max_length=20)),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmado'), ('cancelled', 'Cancelado'), ('completed', 'Finalizado'), ('no_show', 'No se presentó'), ('rescheduled', 'Reprogramado'), ('expired', 'Expirado'), ('refunded', 'Reembolsado'), ('disputed', 'En disputa'), ('awaiting_payment', 'Esperando pago'), ('payment_failed', 'Pago fallido'), ('payment_pending', 'Pago pendiente'), ('payment_refunded', 'Pago reembolsado'), ('payment_disputed', 'Pago en disputa'), ('payment_confirmed', 'Pago confirmado'), ('payment_cancelled', 'Pago cancelado'), ('payment_expired', 'Pago expirado'), ('payment_processing', 'Procesando pago'), ('payment_successful', 'Pago exitoso'), ('payment_failed_refund', 'Reembolso de pago fallido'), ('payment_successful_refund', 'Reembolso de pago exitoso'), ('payment_pending_refund', 'Reembolso de pago pendiente'), ('payment_disputed_refund', 'Reembolso de pago en disputa'), ('payment_confirmed_refund', 'Reembolso de pago confirmado'), ('payment_cancelled_refund', 'Reembolso de pago cancelado'), ('payment_expired_refund', 'Reembolso de pago expirado'), ('payment_processing_refund', 'Procesando reembolso de pago'), ('payment_successful_refund_confirmed', 'Reembolso de pago exitoso confirmado')], default='pending', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AvailabilitySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
