# Generated by Django 5.2.1 on 2025-08-21 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '000X_product_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_promoted',
            field=models.BooleanField(default=False),
        ),
    ]
