# Generated by Django 5.2.1 on 2025-08-21 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_product_is_promoted'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/gallery/')),
                ('video', models.FileField(blank=True, null=True, upload_to='products/gallery/videos/')),
                ('is_header', models.BooleanField(default=False, help_text='Imagen destacada/cabecera del producto')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden en la galería')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
        ),
    ]
